### PR TITLE
add size

### PR DESCRIPTION
**Pull request by yallajosyula**
complete the task

### CODE REVIEW

**Comment by binduborusu** [comment]
completed

**Comment by urlahasini** [comment]
complete

**Comment by sandhyakakita** [comment]
completed

**Comment by urlahasini** [comment]
completed

**Comment by binduborusu** [comment]
you are the great leader  @yallajosyula

**Comment by sirishagotham** [comment]
completed

**Comment by urlahasini** [comment]
completed

**Comment by DarisiLahari** [comment]
completed

**Pull request merged**
